// src/features/cart/AppSlice.js

import { createSlice } from '@reduxjs/toolkit';

// Initial state for the cart
const initialState = {
  showSideBar: true,
};

// Creating the slice for the cart
const AppSlice = createSlice({
  name: 'cart', // Slice name
  initialState, // Initial state for the cart
  reducers: {
    hideSideBar: (state) => {
      state.showSideBar = false;
    },
    showSideBar: (state) => {
      state.showSideBar = true;
    },
  },
});

// Export the actions generated by createSlice
export const { hideSideBar, showSideBar } = AppSlice.actions;

// Export the reducer to be added to the store
export default AppSlice.reducer;
