// src/features/cart/CartSlice.js

import { createSlice } from '@reduxjs/toolkit';

// Initial state for the cart
const initialState = {
  products: []
};

// Creating the slice for the cart
const cartSlice = createSlice({
  name: 'cart', // Slice name
  initialState, // Initial state for the cart
  reducers: {
    addItem: () => {},
    setProducts: (state, action) => { state.products = action.payload}
  },
});

// Export the actions generated by createSlice
export const {addItem, setProducts} = cartSlice.actions;

// Export the reducer to be added to the store
export default cartSlice.reducer;
